"""empty message

Revision ID: 0ccb5f632c81
Revises: 96b6befa7579
Create Date: 2020-02-22 12:33:56.365414

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ccb5f632c81'
down_revision = '96b6befa7579'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sentences',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('example', sa.Text(), nullable=True),
    sa.Column('from_api', sa.Boolean(), nullable=True),
    sa.Column('word_id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['word_id'], ['words.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sentences')
    # ### end Alembic commands ###
