"""empty message

Revision ID: 1612bad75e38
Revises: 0c23a781f0b3
Create Date: 2020-02-20 13:20:32.557136

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1612bad75e38'
down_revision = '0c23a781f0b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_digest', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_digest')
    # ### end Alembic commands ###
