"""empty message

Revision ID: 182d0dfe9711
Revises: aa3d51a835aa
Create Date: 2020-02-20 17:55:06.518361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '182d0dfe9711'
down_revision = 'aa3d51a835aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ideas', sa.Column('question', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ideas', 'question')
    # ### end Alembic commands ###
