"""empty message

Revision ID: 445ea3f878da
Revises: 182d0dfe9711
Create Date: 2020-02-21 18:29:26.896998

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '445ea3f878da'
down_revision = '182d0dfe9711'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('words',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('words')
    # ### end Alembic commands ###
