"""empty message

Revision ID: aa3d51a835aa
Revises: 4d2c9d5a23eb
Create Date: 2020-02-20 17:53:12.786921

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa3d51a835aa'
down_revision = '4d2c9d5a23eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ideas', sa.Column('is_genius', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ideas', 'is_genius')
    # ### end Alembic commands ###
